services:
  - type: web
    name: whatsapp-chatbot-romo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn scripts.whatsapp_bot:app
    envVars:
      - key: META_ACCESS_TOKEN
        sync: false
      - key: META_PHONE_NUMBER_ID
        sync: false
      - key: WEBHOOK_VERIFY_TOKEN
        value: romoseguros123
      - key: PORT
        value: 10000
    healthCheckPath: /health
